/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface CanvasSaverInterface extends ethers.utils.Interface {
  functions: {
    "saveCanvasItem(string)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "saveCanvasItem",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "saveCanvasItem",
    data: BytesLike
  ): Result;

  events: {
    "SaveToLog(address,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "SaveToLog"): EventFragment;
}

export class CanvasSaver extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: CanvasSaverInterface;

  functions: {
    saveCanvasItem(
      itemHash: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "saveCanvasItem(string)"(
      itemHash: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  saveCanvasItem(
    itemHash: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "saveCanvasItem(string)"(
    itemHash: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    saveCanvasItem(itemHash: string, overrides?: CallOverrides): Promise<void>;

    "saveCanvasItem(string)"(
      itemHash: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    SaveToLog(_from: string | null, canvasItem: null): EventFilter;
  };

  estimateGas: {
    saveCanvasItem(itemHash: string, overrides?: Overrides): Promise<BigNumber>;

    "saveCanvasItem(string)"(
      itemHash: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    saveCanvasItem(
      itemHash: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "saveCanvasItem(string)"(
      itemHash: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
