import React, { useState, useEffect, useRef } from 'react'
import { fabric } from 'fabric';
import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Canvas } from 'fabric/fabric-impl';
import dynamic from 'next/dynamic';
import CanvasComponent from '../components/CanvasComponent';

const Home: NextPage = () => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <main className={styles.main}>
        <CanvasComponent />
      </main> */}
      <CanvasComponent />
    </div>
  )
}

export default Home
