/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { CanvasSaver } from "../CanvasSaver";

export class CanvasSaver__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<CanvasSaver> {
    return super.deploy(overrides || {}) as Promise<CanvasSaver>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): CanvasSaver {
    return super.attach(address) as CanvasSaver;
  }
  connect(signer: Signer): CanvasSaver__factory {
    return super.connect(signer) as CanvasSaver__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CanvasSaver {
    return new Contract(address, _abi, signerOrProvider) as CanvasSaver;
  }
}

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "_from",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "canvasItem",
        type: "string",
      },
    ],
    name: "SaveToLog",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "itemHash",
        type: "string",
      },
    ],
    name: "saveCanvasItem",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506100596040518060400160405280601781526020017f4465706c6f79696e6720612043616e766173536176657200000000000000000081525061005e60201b6100921760201c565b61011e565b6100a58160405160240161007291906100c9565b60408051601f198184030181529190526020810180516001600160e01b0390811663104c13eb60e21b179091526100a816565b50565b80516a636f6e736f6c652e6c6f67602083016000808483855afa5050505050565b600060208083528351808285015260005b818110156100f6578581018301518582016040015282016100da565b81811115610108576000604083870101525b50601f01601f1916929092016040019392505050565b61024b8061012d6000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c80635c7702e014610030575b600080fd5b61004361003e36600461010f565b610045565b005b61004e81610092565b336001600160a01b03167fc1c85e5cdfb687344cd0c01ec953bdc879fa4eb7d61419bf18f10c17d90e5df38260405161008791906101c0565b60405180910390a250565b6100d5816040516024016100a691906101c0565b60408051601f198184030181529190526020810180516001600160e01b031663104c13eb60e21b1790526100d8565b50565b80516a636f6e736f6c652e6c6f67602083016000808483855afa5050505050565b634e487b7160e01b600052604160045260246000fd5b60006020828403121561012157600080fd5b813567ffffffffffffffff8082111561013957600080fd5b818401915084601f83011261014d57600080fd5b81358181111561015f5761015f6100f9565b604051601f8201601f19908116603f01168101908382118183101715610187576101876100f9565b816040528281528760208487010111156101a057600080fd5b826020860160208301376000928101602001929092525095945050505050565b600060208083528351808285015260005b818110156101ed578581018301518582016040015282016101d1565b818111156101ff576000604083870101525b50601f01601f191692909201604001939250505056fea264697066735822122065984bc2fe3c58a00f48cc726f504823ed7212507234a24c43d5b373de23d1e264736f6c634300080d0033";
